# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('toi', '0003_auto_20190219_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level1',
            old_name='menu',
            new_name='name',
        ),
        migrations.AddField(
            model_name='level2',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='level3',
            name='name',
            field=models.CharField(default='2019-02-04 07:33:39.953556', max_length=60),
            preserve_default=False,
        ),
    ]
